# Generated by Django 2.0.13 on 2019-03-23 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20190323_1530'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ReadNum',
            new_name='ReadCount',
        ),
    ]
