# Generated by Django 2.0.13 on 2019-03-24 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20190323_1546'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='readcount',
            name='blog',
        ),
        migrations.DeleteModel(
            name='ReadCount',
        ),
    ]
